export enum ZIndex {
  UNUSED = -999,
  BLACK_HOLE_PLATFORM_PULLING_BEAM = -10,
  BLINK_LINE = -1,
  PLATFORM = 0,
  BOOSTER_ATTRIBUTE_ANIMATION = 1,
  PLAYER = 10,
  CHAOS_WILDCARD_GRAVITY_SHOCK = 15,
  EXPLOSION = 100,
  UI_CHAOS_WILDCARD_COOLDOWN = 1000
}
